services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app:ro
      - ./logs:/code/logs
