services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: web-dev
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
      - ./logs:/code/logs
#      - ./dashboard:/code/dashboard
